apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: story-app
  replicas: 1
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story
          image: gcr.io/tradaccs/kub-data:v5
          env:
            - name: STORY_DIR
              value: 'story'
          ports:
            - containerPort: 3000
#          resources:
#            requests:
#              cpu: 200m
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: story-volume-claim
#          emptyDir: {}
#          hostPath:
#            path: /var/story
#            type: DirectoryOrCreate
