apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: story-app
  replicas: 2
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story
          image: gcr.io/tradaccs/kub-data:4
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m