apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-volume-claim
  namespace: default
spec:
  volumeName: story-volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
