apiVersion: v1
kind: Service
metadata:
  name: story-deployment-service
  namespace: default
  labels:
    name: story-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: tradaccs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
