apiVersion: v1
kind: PersistentVolume
metadata:
  name: story-volume
  namespace: default
  labels:
    name: story-volume
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: story-disk
    fsType: ext4
    readOnly: false