apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradaccs-deployment
  namespace: default
  labels:
    name: tradaccs-deployment
spec:
  selector:
    matchLabels:
      app: tradaccs-app
  template:
    metadata:
      labels:
        app: tradaccs-app
    spec:
      containers:
        - name: tradaccs-container
          image: gcr.io/tradaccs/second-deployment:latest
          envFrom:
            - configMapRef:
                name: tradaccs-config
          ports:
            - containerPort: 8080
