apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: gcr.io/tradaccs/kub-consumer:3