version: "3"
services:
  auth:
    build: auth-api
  users:
    build: users-api
    ports: 
      - "8080:8080"
    environment:
      AUTH_API_SERVICE_HOST: 'auth'
  tasks:
    build: tasks-api
    ports: 
      - "8000:8000"
    environment:
      AUTH_API_SERVICE_HOST: 'auth'
      TASKS_FOLDER: tasks