apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: default
  labels:
    name: auth-api
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - port: 80
      targetPort: 80