apiVersion: v1
kind: Service
metadata:
  name: tasks-api
  namespace: default
  labels:
    name: tasks-api
spec:
  type: LoadBalancer
  selector:
    app: tasks-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP