apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-volume-claim
  namespace: default
  labels:
    name: tasks-volume-claim
spec:
  volumeName: tasks-volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
