apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-volume
  namespace: default
  labels:
    name: tasks-volume
spec:
  gcePersistentDisk:
    pdName: task-disk
    readOnly: false
    fsType: ext4
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: standard
  capacity:
    storage: 10Gi