apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: default
  labels:
    name: users-api-service
spec:
  type: LoadBalancer
  selector:
    app: users-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP