apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: default
  labels:
    name: users-api
spec:
  selector:
    matchLabels:
      app: users-api
  replicas: 1
  template:
    metadata:
      name: users-api-pod
      namespace: default
      labels:
        name: users-api-pod
        app: users-api
    spec:
      containers:
        - name: users-api-container
          image: gcr.io/tradaccs/users-api:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                optional: false
                name: users-api-config